AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template that defines lambda functions to automate the process of starting and stopping EC2 instances.

Globals:
  Function:
    Timeout: 10

Parameters:
  InstanceIds:
    Description: Coma separated list of Ids of the instances to automate the Start and stop time
    Type: String
    Default: i-04257cde58a5b074a,i-02e91ff788eaddafb

Resources:
  StartEc2Instance:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: start_ec2_instance/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment: 
        Variables:
          INSTANCE_IDS: !Ref InstanceIds
      Policies:
        - Statement:
          - Sid: AllowStartEc2Instance
            Effect: Allow
            Action:
            - 'ec2:Start*'
            Resource: '*'
      Events:
        CronEveryDay8am:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 * * ? *) # GMT
            Description: Every day at 08:00 
            Enabled: True

  StopEc2Instance:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: stop_ec2_instance/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment: 
        Variables:
          INSTANCE_IDS: !Ref InstanceIds
      Policies:
        - Statement:
          - Sid: AllowStartEc2Instance
            Effect: Allow
            Action:
            - 'ec2:Stop*'
            Resource: '*'          
      Events:
        CronEveryDay10pm:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 * * ? *) # GMT
            Description: Every day at 22:00 
            Enabled: True

